[2024-02-26T19:37:09.721+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cronTrigger.airflow manual__2024-02-26T19:37:03.202178+00:00 [queued]>
[2024-02-26T19:37:09.733+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cronTrigger.airflow manual__2024-02-26T19:37:03.202178+00:00 [queued]>
[2024-02-26T19:37:09.734+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-26T19:37:09.751+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): airflow> on 2024-02-26 19:37:03.202178+00:00
[2024-02-26T19:37:09.758+0000] {standard_task_runner.py:60} INFO - Started process 972 to run task
[2024-02-26T19:37:09.763+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cronTrigger', '***', 'manual__2024-02-26T19:37:03.202178+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/cronTrigger.py', '--cfg-path', '/tmp/tmpd5kqkzkx']
[2024-02-26T19:37:09.768+0000] {standard_task_runner.py:88} INFO - Job 29: Subtask ***
[2024-02-26T19:37:09.831+0000] {task_command.py:423} INFO - Running <TaskInstance: cronTrigger.airflow manual__2024-02-26T19:37:03.202178+00:00 [running]> on host 81dc7f67df81
[2024-02-26T19:37:09.934+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cronTrigger' AIRFLOW_CTX_TASK_ID='***' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T19:37:03.202178+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-26T19:37:03.202178+00:00'
[2024-02-26T19:37:09.956+0000] {python.py:201} INFO - Done. Returned value was: <class 'list'>
[2024-02-26T19:37:09.969+0000] {xcom.py:664} ERROR - Object of type type is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2024-02-26T19:37:09.971+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 180, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'type'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 440, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2980, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 247, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 662, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type type is not JSON serializable
[2024-02-26T19:37:09.989+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=cronTrigger, task_id=***, execution_date=20240226T193703, start_date=20240226T193709, end_date=20240226T193709
[2024-02-26T19:37:10.005+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 29 for task *** (Object of type type is not JSON serializable; 972)
[2024-02-26T19:37:10.056+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-26T19:37:10.086+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
